CardShop/Models/Domain/Card.cs
using CardShop.Models.Attributes;
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardShop.Models.Domain
{
    public class Card
    {
        public int Id { get; set; }
        [Required(ErrorMessage = "A Player is required")]
        public string? Player {  get; set; }
        [ValidateNever]
        public string Description { get; set; } = String.Empty;
        [Required(ErrorMessage = "A Price is required")]
        [Range(1.0d, double.MaxValue, ErrorMessage = "Price must be greater than 0")]
        public decimal? Price { get; set; }
        public bool IsForSale { get; set; } = true;
        [Required(ErrorMessage = "A Card Type is required")]
        public int? TypeId { get; set; }
        [ForeignKey(nameof(TypeId))]
        [ValidateNever]
        public CardType Type { get; set; }
        [Required(ErrorMessage = "A Card Number is required")]
        public uint? Number { get; set; }
        [ValidateNever]
        public string? ImageName { get; set; }
        [Required(ErrorMessage = "A Year is required")]
        [YearRange(1900)]
        public short? Year { get; set; }
        [Required(ErrorMessage = "Card Quality is required")]
        public int? QualityId { get; set; }
        [ForeignKey(nameof(QualityId))]
        [ValidateNever]
        public Quality Quality { get; set; }
        [Required(ErrorMessage = "Card Manufacturer is required")]
        public int? ManufactuererId { get; set; }
        [ForeignKey(nameof(ManufactuererId))]
        [ValidateNever]
        public Manufacturer Manufacturer { get; set; }
        [Required(ErrorMessage = "Card Sport is required")]
        public int? SportId { get; set; }
        [ForeignKey(nameof(SportId))]
        [ValidateNever]
        public Sport Sport { get; set; }
        public IEnumerable<Purchase> Purchases { get; set; }

        public Card()
        {
            Description = String.Empty;
            Purchases = new List<Purchase>();
        }
    }
}

CardShop/Models/Domain/CardType.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace CardShop.Models.Domain
{
    public class CardType
    {
        public int TypeId { get; set; }
        [Required]
        public string? Name { get; set; }
        public ICollection<TradingCard> Cards { get; set; }

        public CardType()
        {
            Cards = new List<TradingCard>();
        }
    }
}

CardShop/Controllers/BagController.cs
using CardShop.Data;
using CardShop.Data.Repository;
using CardShop.Models.Domain;
using CardShop.Models.ExtensionMethods;
using CardShop.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;

namespace CardShop.Controllers
{
    [Authorize]
    public class BagController : Controller
    {
        const string SESSION_KEY = "MyBag";
        private readonly IRepository<TradingCard> _cardDb;

        public BagController(ApplicationDbContext ctx)
        {
            _cardDb = new Repository<TradingCard>(ctx);
        }

        public IActionResult Index()
        {
            List<CartItem> cartItems = HttpContext.Session.Get<List<CartItem>>(SESSION_KEY) ?? new List<CartItem>();

            return View(new ShoppingCartVM()
            {
                CartItems = cartItems,
                TotalAmount = cartItems.Count,
                TotalPrice = cartItems.Sum(c => c.TradingCard.Price.Value * c.Amount)
            });
        }

        [HttpPost]
        public IActionResult AddToBag(int id, int numItems = 1)
        {
            TradingCard? addedItem = _cardDb.Get(id);

            List<CartItem> cartItems = HttpContext.Session.Get<List<CartItem>>(SESSION_KEY) ?? new List<CartItem>();

            CartItem? existingItem = cartItems.FirstOrDefault(c => c.TradingCard.Id == id);

            if (existingItem != null)
            {
                existingItem.Amount += numItems;
            }
            else
            {
                cartItems.Add(new CartItem
                {
                    TradingCard = addedItem,
                    Amount = numItems,
                });
            }

            HttpContext.Session.Set(SESSION_KEY, cartItems);

            return RedirectToAction("Index");
        }

        public IActionResult RemoveFromCart(int id)
        {
            List<CartItem> cartItems = HttpContext.Session.Get<List<CartItem>>(SESSION_KEY) ?? new List<CartItem>();
            CartItem? itemToRemove = cartItems.FirstOrDefault(b => b.TradingCard.Id == id);

            if (itemToRemove != null)
            {
                cartItems.Remove(itemToRemove);
            }

            HttpContext.Session.Set(SESSION_KEY, cartItems);
            return RedirectToAction("Index");
        }

        public IActionResult Checkout()
        {
            List<CartItem> cartItems = HttpContext.Session.Get<List<CartItem>>(SESSION_KEY) ?? new List<CartItem>();
            var domain = "https://localhost:7138";
            var options = new SessionCreateOptions
            {
                BillingAddressCollection = "required",
                LineItems = new List<SessionLineItemOptions>(),
                Mode = "payment",
                SuccessUrl = domain + "/Payment/Success",
                CancelUrl = domain + "",
            };
            foreach (CartItem item in cartItems)
            {
                SessionLineItemOptions sessionLine = new()
                {
                    Price = item.TradingCard.PriceId,
                    Quantity = item.Amount
                };
                options.LineItems.Add(sessionLine);
            }
            var service = new SessionService();
            Session session = service.Create(options);

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }

        [HttpPost]
        public IActionResult ChangeQuantity(int amount, int id)
        {
            List<CartItem> cartItems = HttpContext.Session.Get<List<CartItem>>(SESSION_KEY) ?? new List<CartItem>();
            CartItem? item = cartItems.FirstOrDefault(i => i.TradingCard.Id == id);

            if (item != null)
            {
                item.Amount += amount;
                if (item.Amount < 1)
                {
                    cartItems.Remove(item);
                }
            }

            HttpContext.Session.Set(SESSION_KEY, cartItems);

            return RedirectToAction("Index");
        }

    }
}

CardShop/Controllers/CardController.cs
using CardShop.Data;
using CardShop.Data.Repository;
using CardShop.Models;
using CardShop.Models.Domain;
using CardShop.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace CardShop.Controllers
{
    public class CardController : Controller
    {
        private readonly Repository<TradingCard> _cardDb;

        public CardController(ApplicationDbContext ctx)
        {
            _cardDb = new Repository<TradingCard>(ctx);
        }

        [Route("/Cards/{id?}")]
        public IActionResult Index(string id)
        {
            CardCategoryVM cardsCategoryVM = new()
            {
                Category = id.Length > 3 ? id.Capitalize() : id.ToUpper(),
                Cards = _cardDb.List(new QueryOptions<TradingCard>()
                {
                    OrderBy = c => c.Player,
                    Includes = "Types, Quality, Manufacturer, Sport, Team",
                    Where = c =>  c.Sport.Name.ToUpper() == id.ToUpper() || c.Types.Any(t => t.Name.ToLower() == id) && c.IsForSale == true
                })
            };

            return View(cardsCategoryVM);
        }

        [HttpGet]
        public IActionResult Search(string searchString)
        {
            CardCategoryVM cardsCategoryVM = new()
            {
                Category = searchString,
                Cards = _cardDb.List(new QueryOptions<TradingCard>()
                {
                    OrderBy = c => c.Player,
                    Where = c => c.IsForSale,
                    Includes = "Types, Quality, Manufacturer, Sport, Team",
                }),
                IsSearching = true
            };
            
            if (!String.IsNullOrWhiteSpace(searchString))
            {
                string[] searchTerms = searchString.Split(new char[] { ' ', ',' }, StringSplitOptions.RemoveEmptyEntries);
                cardsCategoryVM.Cards = cardsCategoryVM.Cards.Where(
                c => c.Player.ContainsNoCase(searchString) ||
                c.Description.ContainsNoCase(searchString) ||
                c.Team.Name.ContainsNoCase(searchString) ||
                c.Types.Count(t => searchTerms.Any(term => t.Name.ContainsNoCase(term))) > 0  ||
                c.Manufacturer.Name.ContainsNoCase(searchString) ||
                c.Sport.Name.ContainsNoCase(searchString));
            }else
            {
                cardsCategoryVM.IsSearching = false;
                cardsCategoryVM.Category = "All Cards";
            }
            
            return View("Index", cardsCategoryVM);
        }

        public IActionResult Details(int id)
        {
            TradingCard? card = _cardDb.Get(id);

            if (card == null)
                return View("NotFound");

            TradingCardDetailsVM detailsVM = new()
            {
                Card = card
            };

            return View(detailsVM);
        }
    }
}

CardShop/Controllers/PaymentController.cs
using CardShop.Data;
using CardShop.Data.Repository;
using CardShop.Models.Domain;
using CardShop.Models.ExtensionMethods;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Stripe.Checkout;

namespace CardShop.Controllers
{
    [Authorize]
    public class PaymentController : Controller
    {
        private readonly Repository<TradingCard> cardDb;
        private readonly Repository<Purchase> purchaseDb;
        private readonly UserManager<User> userManager;

        public PaymentController(ApplicationDbContext ctx, UserManager<User> userMan)
        {
            cardDb = new Repository<TradingCard>(ctx);
            purchaseDb = new Repository<Purchase>(ctx);
            userManager = userMan;
        }

        public IActionResult Success()
        {
            List<CartItem> cartItems = HttpContext.Session.Get<List<CartItem>>("MyBag") ?? new List<CartItem>();
            if(cartItems.Count > 0)
            {
                Purchase newPurchase = new Purchase()
                {
                    UserId = userManager.GetUserId(User),
                };
                purchaseDb.Add(newPurchase);
                purchaseDb.Save();
                foreach (var item in cartItems)
                {
                    newPurchase.CardPurchases.Add(new CardPurchase()
                    {
                        CardPurchaseId = 0,
                        TradingCardId = item.TradingCard.Id,
                        PurchaseId = newPurchase.PurchaseId,
                        Quantity = item.Amount
                    });
                    newPurchase.Total += (decimal)item.TradingCard.Price;
                }
                purchaseDb.Save();
            }
            
            HttpContext.Session.Set("MyBag", new List<CartItem>());
            return View();
        }
        public IActionResult Cancel()
        {
            return View("Index", "Home");
        }
        [HttpPost]
        public IActionResult CheckoutNow(int cardId)
        {
            TradingCard? card = cardDb.Get(cardId);

            if (card == null)
                return RedirectToAction("Index", "Home");

            List<CartItem> cartItems = HttpContext.Session.Get<List<CartItem>>("MyBag") ?? new List<CartItem>();
            cartItems.Add(new CartItem()
            {
                TradingCard = card,
                Amount = 1
            });
            HttpContext.Session.Set("MyBag", cartItems);
            var domain = "https://localhost:7138";
            var options = new SessionCreateOptions
            {
                BillingAddressCollection = "required",
                Mode = "payment",
                SuccessUrl = domain + "/Payment/Success",
                CancelUrl = domain + "",
                LineItems = new List<SessionLineItemOptions>
                {
                    new SessionLineItemOptions
                    {
                        Price = card.PriceId,
                        Quantity = 1
                    }
                }
            };
            var service = new SessionService();
            Session session = service.Create(options);

            Response.Headers.Add("Location", session.Url);
            return new StatusCodeResult(303);
        }
    }
}

CardShop/Views/Card/Details.cshtml
@model TradingCardDetailsVM
@{
    ViewBag.Title = $"{Model.Card.Player}";
}

<div class="container mt-5">
    <div class="row">
        <div class="row align-items-stretch">
            <div class="col-md-6">
                <div class="d-flex justify-content-center align-items-center h-100">
                    <img src="~/images/@Model.Card.ImageName" width="50%" />
                </div>
            </div>
            <div class="col-md-6 mt-3">
                <div class="d-flex flex-column h-100 w-100">
                    <h3>@Model.Card.Player</h3>
                    <p class="fs-5">@Model.Card.Price.Value.ToString("C")</p>
                    <p class="text-secondary">@Model.Card.Description</p>
                    <div class="mt-auto">
                        <form asp-controller="Bag" asp-action="AddToBag" method="post">
                            <input hidden value="@Model.Card.Id" name="id" />
                            <button class="w-100 text-center btn btn-dark mb-3 d-flex justify-content-center align-items-center" type="submit">
                                Add to Bag <svg class="ms-2" xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-handbag-fill" viewBox="0 0 16 16">
                                    <path d="M8 1a2 2 0 0 0-2 2v2H5V3a3 3 0 1 1 6 0v2h-1V3a2 2 0 0 0-2-2M5 5H3.36a1.5 1.5 0 0 0-1.483 1.277L.85 13.13A2.5 2.5 0 0 0 3.322 16h9.355a2.5 2.5 0 0 0 2.473-2.87l-1.028-6.853A1.5 1.5 0 0 0 12.64 5H11v1.5a.5.5 0 0 1-1 0V5H6v1.5a.5.5 0 0 1-1 0z" />
                                </svg>
                            </button>
                        </form>
                        <form asp-controller="Payment" asp-action="CheckoutNow">
                            <input hidden value="@Model.Card.Id" name="cardId" />
                            <button class="btn btn-stripe w-100 d-flex justify-content-center" type="submit">
                                Checkout now with <i class="fa-brands fa-stripe"></i>
                            </button>
                        </form>
                        
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>

CardShop/Views/Card/Index.cshtml
@model CardCategoryVM
@{
    ViewBag.Title = $"{Model.Category} Cards";
}

<div class="container">
    <div class=" @(Model.IsSearching ? "" : "text-center")">
        @if (Model.IsSearching)
        {
            <h2 class="mt-3">
                @Model.Cards.Count() result@(Model.Cards.Count() == 1 ? "" : "s") for @Model.Category
            </h2>
        }
        else
        {
            <h2 class="display-3">@Model.Category</h2>
        }

    </div>

    <div class="row">
        @foreach(TradingCard card in Model.Cards)
        {
            if (card.IsForSale)
            {
                <div class="col-md-4 col-sm-6">
                    <div class="product-card mt-3">
                        <a class="card-img" asp-action="Details" asp-route-slug="@card.Slug" asp-route-id="@card.Id">
                            <img src="~/images/@card.ImageName" />
                        </a>
                        <div class="product-card-bottom d-flex flex-column">
                            <p class="mb-0">@card.Player</p>
                            <p class="mb-1">@card.Price.Value.ToString("C")</p>
                        </div>
                        <form asp-controller="Bag" asp-action="AddToBag" class="align-content-end">
                            <input hidden name="id" value="@card.Id" />
                            <button class="btn btn-dark d-flex align-items-center justify-content-center" type="submit">
                                Add to Bag <svg class="ms-2" xmlns="http://www.w3.org/2000/svg" width="17" height="17" fill="currentColor" class="bi bi-handbag-fill" viewBox="0 0 16 16">
                                    <path d="M8 1a2 2 0 0 0-2 2v2H5V3a3 3 0 1 1 6 0v2h-1V3a2 2 0 0 0-2-2M5 5H3.36a1.5 1.5 0 0 0-1.483 1.277L.85 13.13A2.5 2.5 0 0 0 3.322 16h9.355a2.5 2.5 0 0 0 2.473-2.87l-1.028-6.853A1.5 1.5 0 0 0 12.64 5H11v1.5a.5.5 0 0 1-1 0V5H6v1.5a.5.5 0 0 1-1 0z" />
                                </svg>
                            </button>
                        </form>
                    </div>
                </div>
            }
        }
    </div>
</div>