CardShop/Areas/Admin/Controllers/CardTypeController.cs
using CardShop.Areas.Admin.Models.ViewModels;
using CardShop.Data;
using CardShop.Data.Repository;
using CardShop.Models;
using CardShop.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CardShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class CardTypeController : Controller
    {
        private Repository<CardType> cardTypeDb { get; set; }

        public CardTypeController(ApplicationDbContext ctx)
        {
            cardTypeDb = new Repository<CardType>(ctx);
        }

        [Route("{area}/cardtypes")]
        public IActionResult Index(string searchString = "")
        {
            SearchVM<CardType> model = new SearchVM<CardType>()
            {
                Search = searchString,
                Items = cardTypeDb.List(new QueryOptions<CardType>())
            };

            if (searchString != String.Empty)
                model.Items = model.Items.Where(c => c.Name.ContainsNoCase(searchString) ||
                    c.Name.ContainsNoCase(searchString)).ToList();

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            CardType? type = cardTypeDb.Get(id);

            if (type == null)
                return RedirectToAction("Index");

            ManageVM<CardType> vm = new()
            {
                Action = "Edit",
                Item = type
            };

            return View("Manage", vm);
        }

        public IActionResult Add()
        {
            ManageVM<CardType> vm = new()
            {
                Action = "Add",
                Item = new CardType()
            };

            return View("Manage", vm);
        }

        public IActionResult Manage(ManageVM<CardType> model)
        {
            if (ModelState.IsValid)
            {
                if(model.Item.TypeId == 0)
                    cardTypeDb.Add(model.Item);
                else
                    cardTypeDb.Update(model.Item);
                cardTypeDb.Save();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

CardShop/Areas/Admin/Views/CardType/Index.cshtml
@model SearchVM<CardType>
@{
    ViewBag.Title = "Manage Teams";
}

<a class="fs-4" asp-action="Add" asp-controller="CardType" asp-area="Admin">Add Type</a>

<div class="mt-3">
    <form method="get" asp-action="Index" asp-controller="CardType">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search Card Types..." name="searchString" asp-for="Search">
            <button class="btn btn-dark" type="submit">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="m21 21-3.5-3.5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z" />
                </svg>
            </button>
        </div>
    </form>
</div>

@if (Model.Search != String.Empty)
{
    <div>
        <p>@Model.Items.Count() results for @Model.Search</p>
    </div>
}
@if (Model.Items.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (CardType type in Model.Items)
            {
                <tr>
                    <td class="">@type.Name</td>
                    <td>
                        <a asp-action="Edit" asp-controller="CardType" asp-area="Admin" asp-route-id="@type.TypeId" class="btn btn-primary">Manage</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

CardShop/Areas/Admin/Views/CardType/Manage.cshtml
@model ManageVM<CardType>
@{
    ViewBag.Title = Model.Action;
}

<h3>@Model.Action @Model.Item.Name</h3>

<form asp-action="Manage" method="post">
    <div class="mt-3 form-floating">
        <input class="form-control" placeholder="" asp-for="Item.Name"/>
        <label>Card Type</label>
    </div>
    <span class="text-danger" asp-validation-for="Item.Name"></span>
    <input hidden asp-for="@Model.Item.TypeId" />
    <div class="d-flex mt-2">
        <button class="btn btn-primary">Save Changes</button>
        <a class="btn btn-secondary ms-3" asp-action="Index" asp-controller="CardType" asp-area="Admin">Cancel</a>
    </div>
    
</form>