CardShop/Models/Domain/Team.cs
using System.ComponentModel.DataAnnotations;

namespace CardShop.Models.Domain
{
    public class Team
    {
        public int TeamId { get; set; }
        [Required]
        public string? Name { get; set; }
    }
}

CardShop/Areas/Admin/Controllers/TeamController.cs
using CardShop.Areas.Admin.Models.ViewModels;
using CardShop.Data;
using CardShop.Data.Repository;
using CardShop.Models;
using CardShop.Models.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CardShop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class TeamController : Controller
    {
        private Repository<Team> teamDb { get; set; }

        public TeamController(ApplicationDbContext ctx)
        {
            teamDb = new Repository<Team>(ctx);
        }

        [Route("{area}/Teams")]
        public IActionResult Index(string searchString = "")
        {
            SearchVM<Team> model = new SearchVM<Team>()
            {
                Search = searchString,
                Items = teamDb.List(new QueryOptions<Team>())
            };

            if (searchString != String.Empty)
                model.Items = model.Items.Where(c => c.Name.ContainsNoCase(searchString) ||
                    c.Name.ContainsNoCase(searchString)).ToList();

            return View(model);
        }

        public IActionResult Edit(int id)
        {
            Team? team = teamDb.Get(id);

            if (team == null)
                return RedirectToAction("Index");

            ManageVM<Team> vm = new()
            {
                Action = "Edit",
                Item = team
            };

            return View("Manage", vm);
        }

        public IActionResult Add()
        {
            ManageVM<Team> vm = new()
            {
                Action = "Add",
                Item = new Team()
            };

            return View("Manage", vm);
        }

        public IActionResult Manage(ManageVM<Team> model)
        {
            if (ModelState.IsValid)
            {
                if(model.Item.TeamId == 0)
                    teamDb.Add(model.Item);
                else
                    teamDb.Update(model.Item);
                teamDb.Save();
                return RedirectToAction("Index");
            }
            return View(model);
        }
    }
}

CardShop/Areas/Admin/Views/Team/Index.cshtml
@model SearchVM<Team>
@{
    ViewBag.Title = "Manage Teams";
}

<a class="fs-4" asp-action="Add" asp-controller="Team" asp-area="Admin">Add Team</a>

<div class="mt-3">
    <form method="get" asp-action="Index" asp-controller="Team">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Search Teams..." name="searchString" asp-for="Search">
            <button class="btn btn-dark" type="submit">
                <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
                    <path stroke="currentColor" stroke-linecap="round" stroke-width="2" d="m21 21-3.5-3.5M17 10a7 7 0 1 1-14 0 7 7 0 0 1 14 0Z" />
                </svg>
            </button>
        </div>
    </form>
</div>

@if (Model.Search != String.Empty)
{
    <div>
        <p>@Model.Items.Count() results for @Model.Search</p>
    </div>
}
@if (Model.Items.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Team team in Model.Items)
            {
                <tr>
                    <td class="">@team.Name</td>
                    <td>
                        <a asp-action="Edit" asp-controller="Team" asp-area="Admin" asp-route-id="@team.TeamId" class="btn btn-primary">Manage</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}

CardShop/Areas/Admin/Views/Team/Manage.cshtml
@model ManageVM<Team>
@{
    ViewBag.Title = Model.Action;
}

<h3>@Model.Action @Model.Item.Name</h3>

<form asp-action="Manage" method="post">
    <div class="mt-3 form-floating">
        <input class="form-control" placeholder="" asp-for="Item.Name"/>
        <label>Team Name</label>
    </div>
    <span class="text-danger" asp-validation-for="Item.Name"></span>
    <input hidden asp-for="@Model.Item.TeamId" />
    <div class="d-flex mt-2">
        <button class="btn btn-primary">Save Changes</button>
        <a class="btn btn-secondary ms-3" asp-action="Index" asp-asp-controller="Team" asp-area="Admin">Cancel</a>
    </div>
    
</form>